apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense
  region: us-east-1

managedNodeGroups:
  - name: expense
    # Stick to t3.micro for Free Tier (if eligible in your region)
    instanceTypes: ["t3.micro","t3.small","c7i-flex.large","m7i-flex.large"]  # Added more instance types to increase chances of getting spot instances
    desiredCapacity:2        # Reduced to 2 to stay within the 750-hour monthly limit (2 * 375 hrs)
    spot: true